package org.sistema.acompanhamento.tarefas.exception;

public class RelatorioNotFoundException extends RuntimeException {
    public RelatorioNotFoundException(String message) {
        super(message);
    }
}